INSERT INTO clientes (id,nombre,apellido,email,create_at) values ('Alexander','Peña','alex@gmail.com','2002-04-11');
INSERT INTO clientes (id,nombre,apellido,email,create_at) values ('Ana','Lucia','ana112@gmail.com','2008-06-25');
INSERT INTO clientes (nombre,apellido,email,create_at) values ('Ana','Lucia','ana112@gmail.com','2008-06-25');
INSERT INTO clientes (nombre,apellido,email,create_at) values ("Isaac","Craft","placerat.eget@hotmail.org","2022-12-07");
INSERT INTO clientes (nombre,apellido,email,create_at) values ("Amy ","Lynn","lectus.nullam@yahoo.org","2022-11-27");
INSERT INTO clientes (nombre,apellido,email,create_at) values ("Igor"," Haynes","a.magna.lorem@outlook.net","2022-12-05");
INSERT INTO clientes (nombre,apellido,email,create_at) values ("Zia","Cameron","pede.blandit.congue@icloud.com","2022-12-10");
INSERT INTO clientes (nombre,apellido,email,create_at) values ("Odessa","Craig","mi.tempor@protonmail.com","2023-02-26");
INSERT INTO clientes (nombre,apellido,email,create_at) values ("Sean","Calderon","lectus.nullam@yahoo.org","2022-11-27");
INSERT INTO clientes (nombre,apellido,email,create_at) values ("Jackson","Tillman","a.magna.lorem@outlook.net","2022-12-05");